In [14]:
import numpy as np
import random
import pandas as pd

In [10]:
# Initialize matrix A 
A = np.mat([[1, 2, 3],[4, 5, 6] ,[7, 8, 9]] )
# Initialize vector v 
V= np.mat([[1],[1],[1]])
# Multiply A * V
AV =A*V
# from mat to np.array
AV = np.array(AV)
AV

array([[ 6],
       [15],
       [24]])

In [11]:
# Initialize a 3 by 2 matrix 
A = np.mat([[1,2],[3,4],[5,6]])
# Initialize a 2 by 1 matrix 
B = np.mat([[1],[2]])
mult_AB = A*B
mult_AB


matrix([[ 5],
        [11],
        [17]])

In [13]:
# Initialize random matrices A and B 
A = np.mat([[1,2],[4,5]])
B = np.mat([[1,1],[0,2]])
#  Initialize a 2 by 2 identity matrix
I = np.eye(2)
AI = A*I
AI
IA = I*A
IA

matrix([[1., 2.],
        [4., 5.]])

In [30]:
# Initialize random matrices A
A = np.mat("1,2,0;0,5,6;7,0,9") 
A
A_trans = A.T
# Transpose
A_trans
# Inverse
InverseA = np.linalg.inv(A)
InverseA

matrix([[ 0.34883721, -0.13953488,  0.09302326],
        [ 0.3255814 ,  0.06976744, -0.04651163],
        [-0.27131783,  0.10852713,  0.03875969]])